ModernRecrut/ModernRecrut.MVC/Controllers/FavorisController.cs
using Microsoft.AspNetCore.Mvc;
using ModernRecrut.MVC.Helpers;
using ModernRecrut.MVC.Interfaces;
using ModernRecrut.MVC.Models;

namespace ModernRecrut.MVC.Controllers
{
    public class FavorisController : Controller
    {

        private readonly IGestionFavorisService _gestionFavorisServiceProxy;
        private readonly IGestionEmploisService _gestionEmploisServiceProxy;
        private readonly ILogger<FavorisController> _logger;

        public FavorisController(IGestionFavorisService GestionFavorisServiceProxy, IGestionEmploisService GestionEmploisServiceProxy, ILogger<FavorisController> logger)
        {
            _gestionFavorisServiceProxy = GestionFavorisServiceProxy;
            _gestionEmploisServiceProxy = GestionEmploisServiceProxy;
            _logger = logger;
        }
        // GET: FavorisController
        public async Task<ActionResult> Index()
        {

            try
            {
                var offreEmplois = new List<OffreEmploi>();
                var listeFavoris = await _gestionFavorisServiceProxy.ObtenirTout();
                foreach (OffreEmploi favoris in listeFavoris)
                {
                    offreEmplois.Add(favoris);
                }
                return View(offreEmplois);
            }
            catch (Exception e)
            {
                _logger.LogError(CustomLogEvents.Erreur, $"Erreur rencontré à l'obtention de la liste de favoris- {e.Message}");
                return BadRequest();
            }
        }

        // GET: FavorisController/Details/5
        public async Task<ActionResult> Details(int id)
        {

            try
            {
                var offreEmplois = new List<OffreEmploi>();
                var listeFavoris = await _gestionFavorisServiceProxy.ObtenirTout();
                foreach (OffreEmploi favoris in listeFavoris)
                {
                    offreEmplois.Add(favoris);
                }
                if (offreEmplois.Any(e => e.Id == id))
                {
                    return View(offreEmplois.FirstOrDefault(e => e.Id == id));
                }
                else
                {
                    return NotFound();
                }
            }
            catch (HttpRequestException e)
            {
                _logger.LogError(CustomLogEvents.Erreur, $"Erreur rencontré à l'obtention des détails du favoris {id} - {e.Message}");
                return BadRequest();
            }
        }

        // GET: FavorisController/Create
        public async Task<ActionResult> Create(int id)
        {
            try
            {
                var offreEmploi = await _gestionEmploisServiceProxy.Obtenir(id);
                if (offreEmploi != null && ModelState.IsValid)
                {
                    return View(offreEmploi);
                }
                else
                {
                    return NotFound();
                }
            }
            catch (HttpRequestException e)
            {
                _logger.LogError(CustomLogEvents.Erreur, $"Erreur rencontré à la création du favoris {id} - {e.Message}");
                return BadRequest();
            }

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(OffreEmploi offre)
        {
            try
            {
                await _gestionFavorisServiceProxy.Ajouter(offre);
                return RedirectToAction(nameof(Index));
            }
            catch (HttpRequestException e)
            {
                _logger.LogError(CustomLogEvents.Erreur, $"Erreur rencontré à la création du favoris {offre.Id} - {e.Message}");
                return BadRequest();
            }
        }
        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                var offreEmploi = await _gestionEmploisServiceProxy.Obtenir(id);
                if (offreEmploi != null && ModelState.IsValid)
                {
                    return View(offreEmploi);
                }
                else
                {
                    return NotFound();
                }
            }
            catch (HttpRequestException e)
            {
                _logger.LogError(CustomLogEvents.Erreur, $"Erreur rencontré à la suppression du favoris {id} - {e.Message}");
                return BadRequest();
            }
        }
        // GET: FavorisController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(OffreEmploi offreEmploi)
        {
            try
            {
                await _gestionFavorisServiceProxy.Supprimer(offreEmploi.Id);
                return RedirectToAction(nameof(Index));
            }
            catch (HttpRequestException e)
            {
                _logger.LogError(CustomLogEvents.Erreur, $"Erreur rencontré à la suppression du favoris {offreEmploi.Id} - {e.Message}");
                return BadRequest();
            }

        }

    }
}

ModernRecrut/ModernRecrut.MVC/Controllers/OffreEmploisController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ModernRecrut.MVC.Helpers;
using ModernRecrut.MVC.Interfaces;
using ModernRecrut.MVC.Models;

namespace ModernRecrut.MVC.Controllers
{
    public class OffreEmploisController : Controller
    {
        public readonly IGestionEmploisService _gestionEmploisService;
        public readonly ILogger<OffreEmploisController> _logger;

        public OffreEmploisController(IGestionEmploisService gestionEmploisService, ILogger<OffreEmploisController> logger)
        {
            _gestionEmploisService = gestionEmploisService;
            _logger = logger;
        }
        // GET: OffreEmploisController

        public async Task<ActionResult> Index()
        {
            try
            {
                var offreEmplois = await _gestionEmploisService.ObtenirTout();
                return View(offreEmplois);
            }
            catch (HttpRequestException e)
            {
                _logger.LogError(CustomLogEvents.Erreur, $"Erreur rencontré à l'obtention des offres d'emplois - {e.Message}");
                return BadRequest();
            }
        }

        // GET: OffreEmploisController/Details/5

        public async Task<ActionResult> Details(int id)
        {
            try
            {
                var offreEmploi = await _gestionEmploisService.Obtenir(id);

                if (offreEmploi == null)
                {
                    return NotFound();
                }

                return View(offreEmploi);
            }
            catch (HttpRequestException e)
            {
                _logger.LogError(CustomLogEvents.Erreur, $"Erreur rencontré à l'obtention des détails de l'offre d'emplois {id} - {e.Message}");
                return BadRequest();
            }

        }

        // GET: OffreEmploisController/Create

        public ActionResult Create()
        {
            return View();
        }

        // POST: OffreEmploisController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(OffreEmploi offreEmploi)
        {
            try
            {
                if (offreEmploi.DateAffichage > DateTime.Now)
                    ModelState.AddModelError("DateAffichage", "La date d'affichage doit etre inférieure ou égale a la date du jour ");

                if (offreEmploi.DateDeFin < DateTime.Now)
                    ModelState.AddModelError("DateDeFin", "La date de fin doit etre supérieure ou égale a la date du jour ");

                if (ModelState.IsValid)
                {
                    await _gestionEmploisService.Ajouter(offreEmploi);

                    return RedirectToAction(nameof(Index));

                }

                return View();
            }
            catch (HttpRequestException e)
            {
                _logger.LogError(CustomLogEvents.Erreur, $"Erreur rencontré à la création de l'offre d'emplois {offreEmploi.Id} - {e.Message}");
                return BadRequest();
            }

        }

        // GET: OffreEmploisController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            try
            {
                var offreEmploi = await _gestionEmploisService.Obtenir(id);
                if (offreEmploi == null)
                {
                    _logger.LogInformation(CustomLogEvents.NotFound, $"Erreur rencontré à la modification de l'offre d'emplois {offreEmploi.Id}");
                    return NotFound();
                }
                return View(offreEmploi);
            }
            catch (HttpRequestException e)
            {
                _logger.LogError(CustomLogEvents.Erreur, $"Erreur rencontré à la modification de l'offre d'emplois {id} - {e.Message}");
                return BadRequest();
            }
        }

        // POST: OffreEmploisController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, OffreEmploi offreEmploi)
        {
            try
            {
                if (offreEmploi.DateAffichage > DateTime.Now)
                    ModelState.AddModelError("DateAffichage", "La date d'affichage doit etre inférieure ou égale a la date du jour ");

                if (offreEmploi.DateDeFin < DateTime.Now)
                    ModelState.AddModelError("DateDeFin", "La date de fin doit etre supérieure ou égale a la date du jour ");

                if (ModelState.IsValid)
                {
                    try
                    {
                        await _gestionEmploisService.Modifier(offreEmploi);
                    }
                    catch (DbUpdateConcurrencyException e)
                    {
                        _logger.LogError(CustomLogEvents.Erreur, $"Erreur rencontré à la modification de l'offre d'emplois {offreEmploi.Id} - {e.Message}");
                        if (!OffreEmploiExists(offreEmploi.Id))
                        {
                            _logger.LogError(CustomLogEvents.NotFound, $"Erreur rencontré à la modification de l'offre d'emplois {offreEmploi.Id} - {e.Message}");
                            return NotFound();
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
                return View(offreEmploi);
            }
            catch (HttpRequestException e)
            {
                _logger.LogError(CustomLogEvents.Erreur, $"Erreur rencontré à la modification de l'offre d'emplois {id} - {e.Message}");
                return BadRequest();
            }
        }

        // GET: OffreEmploisController/Delete/5

        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                var offreEmploi = await _gestionEmploisService.Obtenir(id);
                if (offreEmploi != null)
                {
                    return View(offreEmploi);
                }
                _logger.LogInformation(CustomLogEvents.NotFound, $"Erreur rencontré à la suppression de l'offre d'emplois {offreEmploi.Id}");
                return NotFound();
            }
            catch (HttpRequestException e)
            {
                _logger.LogError(CustomLogEvents.Erreur, $"Erreur rencontré à la suppression de l'offre d'emplois {id} - {e.Message}");
                return BadRequest();
            }
        }

        // POST: OffreEmploisController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(OffreEmploi offreEmploi)
        {
            try
            {
                await _gestionEmploisService.Supprimer(offreEmploi.Id);

                return RedirectToAction(nameof(Index));
            }
            catch (HttpRequestException e)
            {
                _logger.LogError(CustomLogEvents.Erreur, $"Erreur rencontré à la suppression de l'offre d'emplois {offreEmploi.Id} - {e.Message}");
                return BadRequest();
            }
        }

        private bool OffreEmploiExists(int id)
        {
            try
            {
                return _gestionEmploisService.ObtenirTout().Result.Any(e => e.Id == id);
            }
            catch (HttpRequestException e)
            {
                _logger.LogError(CustomLogEvents.Erreur, $"Erreur rencontré à la suppression de l'offre d'emplois {id} - {e.Message}");
                return false;
            }
        }
    }
}

ModernRecrut/ModernRecrut.MVC/Views/Favoris/Create.cshtml
@model ModernRecrut.MVC.Models.OffreEmploi

@{
    ViewData["Title"] = "Confirmation de l'offre d'emploi à rajouter à vos favoris";
}

<h1>Confirmation de l'offre d'emploi à rajouter à vos favoris</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" readonly />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateAffichage" class="control-label"></label>
                <input asp-for="DateAffichage" class="form-control" readonly />
                <span asp-validation-for="DateAffichage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateDeFin" class="control-label"></label>
                <input asp-for="DateDeFin" class="form-control" disabled />
                <span asp-validation-for="DateDeFin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" readonly />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Poste" class="control-label"></label>
                <input asp-for="Poste" class="form-control" readonly />
                <span asp-validation-for="Poste" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" readonly />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Confirmer" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Retour à votre liste de favoris</a>
    <a asp-controller="OffreEmplois" asp-action="Index">Retour aux offres d'emplois</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ModernRecrut/ModernRecrut.MVC/Views/Favoris/Delete.cshtml
@model ModernRecrut.MVC.Models.OffreEmploi

@{
    ViewData["Title"] = "Delete";
}

<h1>Suppression d'un favoris</h1>

<h3>Êtes-vous certain de vouloir supprimer cette offre d'emploi de vos favoris?</h3>
<div>    
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateAffichage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateAffichage)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateDeFin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateDeFin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Poste)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Poste)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Suppression" class="btn btn-danger" /> |
        <a asp-action="Index">Retour à votre liste de favoris</a>        
    </form>
</div>

ModernRecrut/ModernRecrut.MVC/Views/Favoris/Details.cshtml
@model ModernRecrut.MVC.Models.OffreEmploi

@{
    ViewData["Title"] = "Details";
}

<h1>Details de l'offre</h1>

<div>    
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateAffichage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateAffichage)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateDeFin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateDeFin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Poste)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Poste)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
    </dl>
</div>
<div>
    <a asp-area="" asp-controller="Favoris" asp-action="Delete" asp-route-id="@Model.Id">Supprimer</a> |
    <a asp-action="Index">Retour à votre liste de favoris</a>
</div>

ModernRecrut/ModernRecrut.MVC/Views/Favoris/Index.cshtml
@model IEnumerable<ModernRecrut.MVC.Models.OffreEmploi>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nom)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    <a asp-area="" asp-controller="Favoris" asp-action="Details" asp-route-id="@item.Id">Details</a>
                    <a asp-area="" asp-controller="Favoris" asp-action="Delete" asp-route-id="@item.Id">Supprimer</a>
                </td>
            </tr>
        }
    </tbody>
</table>