ModernRecrut/ModernRecrut.MVC/Models/OffreEmploi.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace ModernRecrut.MVC.Models
{
    public class OffreEmploi
    {
        public int Id { get; set; }
        [Required]
        [DisplayName("Date d'affichage")]
        public DateTime DateAffichage { get; set; }
        [Required]
        [DisplayName("Date de fin")]
        public DateTime DateDeFin { get; set; }
        [Required]
        public string? Description { get; set; }
        [Required]
        public string? Poste { get; set; }
        [Required]
        public string? Nom { get; set; }
    }
}

ModernRecrut/ModernRecrut.MVC/Controllers/FavorisController.cs
using Microsoft.AspNetCore.Mvc;
using ModernRecrut.MVC.Helpers;
using ModernRecrut.MVC.Interfaces;
using ModernRecrut.MVC.Models;

namespace ModernRecrut.MVC.Controllers
{
    public class FavorisController : Controller
    {

        private readonly IGestionFavorisService _gestionFavorisServiceProxy;
        private readonly IGestionEmploisService _gestionEmploisServiceProxy;
        private readonly ILogger<FavorisController> _logger;

        public FavorisController(IGestionFavorisService GestionFavorisServiceProxy, IGestionEmploisService GestionEmploisServiceProxy, ILogger<FavorisController> logger)
        {
            _gestionFavorisServiceProxy = GestionFavorisServiceProxy;
            _gestionEmploisServiceProxy = GestionEmploisServiceProxy;
            _logger = logger;
        }
        // GET: FavorisController
        public async Task<ActionResult> Index()
        {

            try
            {
                var offreEmplois = new List<OffreEmploi>();
                var listeFavoris = await _gestionFavorisServiceProxy.ObtenirTout();
                foreach (OffreEmploi favoris in listeFavoris)
                {
                    offreEmplois.Add(favoris);
                }
                return View(offreEmplois);
            }
            catch (Exception e)
            {
                _logger.LogError(CustomLogEvents.Erreur, $"Erreur rencontré à l'obtention de la liste de favoris- {e.Message}");
                return BadRequest();
            }
        }

        // GET: FavorisController/Details/5
        public async Task<ActionResult> Details(int id)
        {

            try
            {
                var offreEmplois = new List<OffreEmploi>();
                var listeFavoris = await _gestionFavorisServiceProxy.ObtenirTout();
                foreach (OffreEmploi favoris in listeFavoris)
                {
                    offreEmplois.Add(favoris);
                }
                if (offreEmplois.Any(e => e.Id == id))
                {
                    return View(offreEmplois.FirstOrDefault(e => e.Id == id));
                }
                else
                {
                    return NotFound();
                }
            }
            catch (HttpRequestException e)
            {
                _logger.LogError(CustomLogEvents.Erreur, $"Erreur rencontré à l'obtention des détails du favoris {id} - {e.Message}");
                return BadRequest();
            }
        }

        // GET: FavorisController/Create
        public async Task<ActionResult> Create(int id)
        {
            try
            {
                var offreEmploi = await _gestionEmploisServiceProxy.Obtenir(id);
                if (offreEmploi != null && ModelState.IsValid)
                {
                    return View(offreEmploi);
                }
                else
                {
                    return NotFound();
                }
            }
            catch (HttpRequestException e)
            {
                _logger.LogError(CustomLogEvents.Erreur, $"Erreur rencontré à la création du favoris {id} - {e.Message}");
                return BadRequest();
            }

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(OffreEmploi offre)
        {
            try
            {
                await _gestionFavorisServiceProxy.Ajouter(offre);
                return RedirectToAction(nameof(Index));
            }
            catch (HttpRequestException e)
            {
                _logger.LogError(CustomLogEvents.Erreur, $"Erreur rencontré à la création du favoris {offre.Id} - {e.Message}");
                return BadRequest();
            }
        }
        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                var offreEmploi = await _gestionEmploisServiceProxy.Obtenir(id);
                if (offreEmploi != null && ModelState.IsValid)
                {
                    return View(offreEmploi);
                }
                else
                {
                    return NotFound();
                }
            }
            catch (HttpRequestException e)
            {
                _logger.LogError(CustomLogEvents.Erreur, $"Erreur rencontré à la suppression du favoris {id} - {e.Message}");
                return BadRequest();
            }
        }
        // GET: FavorisController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(OffreEmploi offreEmploi)
        {
            try
            {
                await _gestionFavorisServiceProxy.Supprimer(offreEmploi.Id);
                return RedirectToAction(nameof(Index));
            }
            catch (HttpRequestException e)
            {
                _logger.LogError(CustomLogEvents.Erreur, $"Erreur rencontré à la suppression du favoris {offreEmploi.Id} - {e.Message}");
                return BadRequest();
            }

        }

    }
}

ModernRecrut/ModernRecrut.MVC/Controllers/PostulationController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using ModernRecrut.MVC.Areas.Identity.Data;
using ModernRecrut.MVC.Helpers;
using ModernRecrut.MVC.Interfaces;
using ModernRecrut.MVC.Models;


namespace ModernRecrut.MVC.Controllers
{
    public class PostulationController : Controller
    {

        private readonly IGestionEmploisService _gestionEmploisServiceProxy;
        private readonly IGestionPostulationsService _gestionPostulationsServiceProxy;
        private readonly IGestionDocumentsService _gestionDocumentsServiceProxy;
        private readonly UserManager<ModernRecrutMVCUser> _userManager;
        private readonly IWebHostEnvironment _env;
        private readonly ILogger<PostulationController> _logger;
       

        public PostulationController(IGestionEmploisService gestionEmploisServiceProxy, IWebHostEnvironment env, IGestionPostulationsService gestionPostulationsServiceProxy, UserManager<ModernRecrutMVCUser> userManager, IGestionDocumentsService gestionDocumentsServiceProxy, ILogger<PostulationController> logger)
        {
            _gestionEmploisServiceProxy = gestionEmploisServiceProxy;
            _gestionPostulationsServiceProxy = gestionPostulationsServiceProxy;
            _userManager = userManager;
            _env = env;
            _gestionDocumentsServiceProxy = gestionDocumentsServiceProxy;
            _logger = logger;

        }


        // GET: PostulationController
        [Authorize]
        public async Task<ActionResult> ListePostulations()
        {
            try
            {
                var postulations = await _gestionPostulationsServiceProxy.ObtenirTout();
                return View(postulations);
            }
            catch (HttpRequestException e)
            {
                _logger.LogError(CustomLogEvents.Erreur, $"Erreur lors de la récupération des postulations - {e.Message} ");
                return BadRequest();
            }
        }

        // GET: PostulationController/Details/5
        [Authorize]
        [Authorize]
        public async Task<ActionResult> Notes(int id)
        {
            try
            {
                var postulation = await _gestionPostulationsServiceProxy.Obtenir(id);

                if (postulation == null)
                {
                    return NotFound();
                }

                return View(postulation);
            }
            catch (HttpRequestException e)
            {
                _logger.LogError(CustomLogEvents.Erreur, $"Erreur lors de la récupération de la postulation {id} - {e.Message} ");
                return BadRequest();
            }
        }

        // GET: PostulationController/Create
        [Authorize]
        public async Task<ActionResult> Postuler()
        {
            var numeroIdentifiant = await _userManager.FindByNameAsync(User.Identity.Name);

            

            ViewBag.NumeroIdentifiant = numeroIdentifiant.Id;

            return View();
        }

        // POST: PostulationController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Postuler(Postulation postulation)
        {            
                ModelState.Remove("IdCandidat");
                try
                {
                    if (User.Identity.IsAuthenticated)
                    {
                        var user = await _userManager.FindByNameAsync(User.Identity.Name);
                        
                        try
                        {
                            var listeFichiers = await _gestionDocumentsServiceProxy.ObtenirTout(user.Id);
                            bool cvTrouve = false;

                            foreach (var fichier in listeFichiers)
                            {
                                if (fichier.Contains(user.Id + "_Cv_"))
                                {
                                    cvTrouve = true;
                                    break;
                                }
                            }


                            if (cvTrouve == false)
                            {
                                ModelState.AddModelError("cvTrouve", "Vous devez avoir un CV");
                            }
                        }
                        catch (NullReferenceException e)
                        {
                            _logger.LogError(CustomLogEvents.Erreur, $"Erreur lors de la récupération des documents de l'utilisateur {user.Id} - {e.Message} ");
                            return NotFound(e.Message);
                        }
                    }
                }
                catch (NullReferenceException e)
                {
                    _logger.LogError(CustomLogEvents.Erreur, $"Erreur l'utilisateur n'est pas authentifié");
                    return NotFound(e.Message);
                }

                if (postulation.PretentionSalariale > 150000)
                    ModelState.AddModelError("PretentionSalariale", "Votre prétentation salariale est au-delà de nos limites");

                if (postulation.DateDisponibilite < DateTime.Today || postulation.DateDisponibilite >= DateTime.Today.AddDays(45))
                    ModelState.AddModelError("DateDisponibilite", $"La date de disponibilité doit être supérieure à la date du jour et inférieure au {DateTime.Today} + 45 jours >");

                if (ModelState.IsValid)
                {
                    await _gestionPostulationsServiceProxy.Ajouter(postulation);

                    return RedirectToAction(nameof(ListePostulations));
                }

                return View(postulation);           
        }

        // GET: PostulationController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            try
            {
                var postulation = await _gestionPostulationsServiceProxy.Obtenir(id);

                if (postulation == null)
                {
                    return NotFound();
                }

                return View(postulation);
            }
            catch (HttpRequestException e)
            {
                _logger.LogError(CustomLogEvents.Erreur, $"Erreur lors la modification d'une postulation {id} - {e.Message}");
                return BadRequest(e.Message);
            }

        }

        // POST: PostulationController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, Postulation postulation)
        {
            try
            {
                if (postulation.DateDisponibilite < DateTime.Today.AddDays(-5) || postulation.DateDisponibilite > DateTime.Today.AddDays(5))
                    ModelState.AddModelError("DateDisponibilite", $"La date de disponibilité doit être supérieure à la date du jour et inférieure au {DateTime.Today} + 5 jours >");

                if (ModelState.IsValid)
                {
                    try
                    {
                        await _gestionPostulationsServiceProxy.Modifier(postulation);
                    }
                    catch (DbUpdateConcurrencyException e)
                    {
                        _logger.LogError(CustomLogEvents.Erreur, $"Erreur lors de l'appel de l'api pour modification de la postulation {postulation.Id} : {e.Message}");
                        return View(postulation);
                    }
                    return RedirectToAction(nameof(Index));
                }
                return View(postulation);
            }
            catch (HttpRequestException e)
            {
                _logger.LogError(CustomLogEvents.Erreur, $"Erreur lors la modification d'une postulation {id} - {e.Message}");
                return BadRequest(e.Message);
            }
        }

        // GET: PostulationController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                var offreEmploi = await _gestionPostulationsServiceProxy.Obtenir(id);
                if (offreEmploi != null)
                {
                    return View(offreEmploi);
                }
                return NotFound();
            }
            catch (HttpRequestException e)
            {
                _logger.LogError(CustomLogEvents.Erreur, $"Erreur lors de l'appel de l'api pour obtention d'une postulation {id} - {e.Message}");
                return BadRequest();
            }
        }

        // POST: PostulationController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(Postulation postulation)
        {
            try
            {
                if (postulation.DateDisponibilite < DateTime.Today.AddDays(-5) || postulation.DateDisponibilite > DateTime.Today.AddDays(5))
                    ModelState.AddModelError("DateDisponibilite", $"La date de disponibilité doit être supérieure à la date du jour et inférieure au {DateTime.Today} + 5 jours >");
                if (ModelState.IsValid)
                {
                    try
                    {
                        await _gestionPostulationsServiceProxy.Supprimer(postulation.Id);
                    }
                    catch (HttpRequestException e)
                    {
                        _logger.LogError(CustomLogEvents.Erreur, $"Erreur lors de l'appel de l'api pour suppression de la postulation {postulation.Id} : {e.Message}");
                        return View(postulation);
                    }

                    return RedirectToAction(nameof(Index));
                }

                return View(postulation);
            }
            catch (HttpRequestException e)
            {

ModernRecrut/ModernRecrut.MVC/Views/OffreEmplois/Create.cshtml
@model ModernRecrut.MVC.Models.OffreEmploi

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>OffreEmploi</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>            
            <div class="form-group">
                <label asp-for="DateAffichage" class="control-label"></label>
                <input asp-for="DateAffichage" class="form-control" />
                <span asp-validation-for="DateAffichage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateDeFin" class="control-label"></label>
                <input asp-for="DateDeFin" class="form-control" />
                <span asp-validation-for="DateDeFin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Poste" class="control-label"></label>
                <input asp-for="Poste" class="form-control" />
                <span asp-validation-for="Poste" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ModernRecrut/ModernRecrut.MVC/Views/OffreEmplois/Delete.cshtml
@model ModernRecrut.MVC.Models.OffreEmploi

@{
    ViewData["Title"] = "Delete";
}

<h1>Suppression d'une offre d'emploi'</h1>

<h3>Êtes-vous certain de vouloir supprimer cette offre d'emploi?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateAffichage)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateAffichage)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateDeFin)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateDeFin)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Poste)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Poste)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="submit" value="Suppression" class="btn btn-danger" /> |
        <a asp-action="Index">Retour à votre liste de favoris</a>
    </form>
</div>

ModernRecrut/ModernRecrut.MVC/Views/OffreEmplois/Details.cshtml
@model ModernRecrut.MVC.Models.OffreEmploi

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>OffreEmploi</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateAffichage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateAffichage)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateDeFin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateDeFin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Poste)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Poste)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
    </dl>
</div>
<div>
    <a asp-area="" asp-controller="Favoris" asp-action="Create" asp-route-id="@Model.Id">Ajout a vos favoris</a> |   
    @Html.ActionLink("Postuler", "Postuler", "Postulation" , new { id=Model.Id })
    <a asp-action="Index">Back to List</a>
</div>

ModernRecrut/ModernRecrut.MVC/Views/OffreEmplois/Edit.cshtml
@model ModernRecrut.MVC.Models.OffreEmploi

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>OffreEmploi</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateAffichage" class="control-label"></label>
                <input asp-for="DateAffichage" class="form-control" />
                <span asp-validation-for="DateAffichage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateDeFin" class="control-label"></label>
                <input asp-for="DateDeFin" class="form-control" />
                <span asp-validation-for="DateDeFin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Poste" class="control-label"></label>
                <input asp-for="Poste" class="form-control" />
                <span asp-validation-for="Poste" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a> |
    @Html.ActionLink("Edit", "Edit", new {  id = Model.Id  }) |
</div>

ModernRecrut/ModernRecrut.MVC/Views/OffreEmplois/Index.cshtml
@using ModernRecrut.MVC.Models
@model IEnumerable<ModernRecrut.MVC.Models.OffreEmploi>
@{
    ViewData["Title"] = "Index";

    var recherche = Context.Request.Query["recherche"].ToString();
    var liste = new List<OffreEmploi>();
    
    liste = Model.ToList();


    if (!string.IsNullOrEmpty(recherche))
    {
        liste = liste.Where(v => v.Poste.Contains(recherche)).ToList();
    }
}

<h1>Liste des postes</h1>

<p>
    <a asp-action="Create">Ajout d'un nouveau poste</a>
</p>
<form>
    <div class="form-actions no-color">
        <p>            
            <input type="text" name="recherche" value="@recherche" placeholder="Recherche par poste"/>
            <input type="submit" value="Rechercher" class="btn btn-primary" />           
        </p>
    </div>
</form>


<table class="table">
    <thead>
        <tr>
            
            <th>
                @Html.DisplayNameFor(model => model.Nom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Poste)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateAffichage)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateDeFin)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in liste)
        {
            <tr>
                
                <td>
                    @Html.DisplayFor(modelItem => item.Nom)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Poste)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateAffichage)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateDeFin)
                </td>
                <td>
                    @Html.ActionLink("Modifier", "Edit", new { id=item.Id  }) |
                    @Html.ActionLink("Détails", "Details", new { id=item.Id }) |
                    @Html.ActionLink("Supression", "Delete", new { id=item.Id }) |
                    @Html.ActionLink("Ajouter au favoris", "Create", "Favoris" , new { id=item.Id }) |
                    @Html.ActionLink("Postuler", "Postuler", "Postulation" , new { id=item.Id })
                </td>
            </tr>
        }
    </tbody>    
</table>

<p>
    @Html.ActionLink("Retourner à la liste complète", "Index")
</p>